import type { Metadata } from "next";
import App from "./app";
import "./globals.css";
import { Theme } from '@radix-ui/themes';
import '@radix-ui/themes/styles.css';
import { WalletSelectorContextProvider } from '@/contexts/WalletSelectorContext';
import '@near-wallet-selector/modal-ui/styles.css';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <WalletSelectorContextProvider>
          <Theme appearance="dark" accentColor="blue">
            <main className="min-h-screen">
              {children}
            </main>
          </Theme>
        </WalletSelectorContextProvider>
      </body>
    </html>
  );
}
