import type { Metadata } from "next";
import App from "./app";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout() {
  return (
    <html lang="en">
      <body className={`antialiased h-screen w-screen`}>
        <App />
      </body>
    </html>
  );
}
